export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const USER_ERROR = 'USER_ERROR';

export const CHANGE_FRAME = 'CHANGE_FRAME';
export const CHOOSE_STICKER = 'CHOOSE_STICKER';
export const ADD_COORDS = 'ADD_COORDS';
export const CLEAR_PICTURE = 'CLEAR_PICTURE';
export const SET_CANVAS_DATA = 'SET_CANVAS_DATA';
export const CLEAR_COORDS = 'CLEAR_COORDS';

export const MAIN_GET_ALL_PICTURES = 'MAIN_GET_ALL_PICTURES';
export const MAIN_DELETE_PICTURE = 'MAIN_DELETE_PICTURE';
export const MAIN_GET_ERRORS = 'MAIN_GET_ERRORS';
export const MAIN_LIKE_PICTURE = 'MAIN_LIKE_PICTURE';
export const MAIN_ADD_COMMENT = 'MAIN_ADD_COMMENT';
export const MAIN_SAVE_PICTURE = 'MAIN_SAVE_PICTURE';
export const MAIN_GET_FIVE_PICTURES = 'MAIN_GET_FIVE_PICTURES';
export const MAIN_DELETE_PICTURE_LANDING = 'MAIN_DELETE_PICTURE_LANDING';
